### ISSUE TITLE
GetOnlinePlayers() does not return an indexed array

### ISSUE THREAD

**Issue by Awzaw** [Ad5001/PlayerSelectors#2]
https://github.com/Ad5001/PlayerSelectors/blob/6a5ddcd42da3030fbe1e0356c3fbfea17e78657f/src/Ad5001/PlayerSelectors/selector/ClosestPlayer.php#L30

This won't work because the array returned by GetOnlinePlayers() is not an indexed array, but an associative array with the players rawUUID as the key:

https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Server.php#L2306

Also, your function needs to return an array with the name of the player, not the Player object.

**Comment by Ad5001** [comment]
Interesting... I did not know this. Well, we learn new things everyday :) Will fix it asap.

**Comment by Ad5001** [comment]
This bug has been fixed in the latest commit.
